### ISSUE TITLE
i beg you please tell how to run the project in windows

### ISSUE THREAD

**Issue by BrandedAlok** [buckyroberts/Turtle#29]
i beg you please tell how to run the project in windows

(C:\Users\user\Anaconda3) C:\Turtle-master\Single_Client>python client.py
Socket connection error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File "client.py", line 52, in <module>
    main()
  File "client.py", line 49, in main
    receive_commands()
  File "client.py", line 34, in receive_commands
    data = s.recv(1024)
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied

**Comment by Covalent5** [comment]
try starting the client first and then the server! if not let me know, I can try to reproduce!
